//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company
{
    using System;
    using System.Collections.Generic;
    
    public partial class Move_To
    {
        public int I_Code { get; set; }
        public string FromWH_Nm { get; set; }
        public string ToWH_Nm { get; set; }
        public Nullable<int> Quantity { get; set; }
        public System.DateTime Move_Date { get; set; }
        public System.DateTime Production_Date { get; set; }
        public Nullable<System.DateTime> Expire_Date { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual WareHouse WareHouse { get; set; }
        public virtual WareHouse WareHouse1 { get; set; }
    }
}
