//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permetion_Export
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Permetion_Export()
        {
            this.Export_Quantity = new HashSet<Export_Quantity>();
        }
    
        public int Per_Num_E { get; set; }
        public int I_Code { get; set; }
        public string WH_Name { get; set; }
        public string Cus_Email { get; set; }
        public Nullable<System.DateTime> Per_DateE { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Export_Quantity> Export_Quantity { get; set; }
        public virtual Item Item { get; set; }
        public virtual WareHouse WareHouse { get; set; }
    }
}
